.TH "audiosensor/AudioSensor.h" 3 "Fre Mai 5 2017" "WFO: Arduino Informatik-Schulprojekt" \" -*- nroff -*-
.ad l
.nh
.SH NAME
audiosensor/AudioSensor.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Klassen"

.in +1c
.ti -1c
.RI "class \fBAudioSensor\fP"
.br
.RI "\fIDiese Klasse ermöglicht die Verwendung des Audiosensor\&. \fP"
.in -1c
.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für WFO: Arduino Informatik-Schulprojekt aus dem Quellcode\&.
