.TH "led/LED.h" 3 "Fre Mai 5 2017" "WFO: Arduino Informatik-Schulprojekt" \" -*- nroff -*-
.ad l
.nh
.SH NAME
led/LED.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Klassen"

.in +1c
.ti -1c
.RI "class \fBLED\fP"
.br
.RI "\fIDiese Klasse ermöglicht die Verwendung von LEDs\&. Wichtig hierbei ist, dass ein 220 Ohm Widerstand in Reihe zu schalten ist\&. Außerdem ist es notwendig, dass das zweite Bein der \fBLED\fP mit Masse(GND) verbunden ist\&. \fP"
.in -1c
.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für WFO: Arduino Informatik-Schulprojekt aus dem Quellcode\&.
