.TH "taster/Taster.h" 3 "Fre Mai 5 2017" "WFO: Arduino Informatik-Schulprojekt" \" -*- nroff -*-
.ad l
.nh
.SH NAME
taster/Taster.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Klassen"

.in +1c
.ti -1c
.RI "class \fBTaster\fP"
.br
.RI "\fIDiese Klasse ermöglicht die Verwendung von Tastern\&. Wichtig hierbei ist, dass das Schalten gegen Masse (GND) erfolgt\&. \fP"
.in -1c
.SS "Variablen"

.in +1c
.ti -1c
.RI "volatile bool \fBstate\fP = false"
.br
.ti -1c
.RI "volatile bool \fBstate2\fP = false"
.br
.in -1c
.SH "Variablen-Dokumentation"
.PP 
.SS "volatile bool state = false"

.SS "volatile bool state2 = false"

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für WFO: Arduino Informatik-Schulprojekt aus dem Quellcode\&.
