.TH "temperatur/TemperaturSensor.h" 3 "Fre Mai 5 2017" "WFO: Arduino Informatik-Schulprojekt" \" -*- nroff -*-
.ad l
.nh
.SH NAME
temperatur/TemperaturSensor.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Klassen"

.in +1c
.ti -1c
.RI "class \fBTemperaturSensor\fP"
.br
.RI "\fIDiese Klasse ermöglicht die Verwendung des Temperatursensors\&. Wichtig hierbei ist, dass Pin-1 mit Masse (GND), Pin-2 mit PWM-Arduinoeingang und Pin-3 mit Versorgungsspannung (+5V) verbunden sind\&. ( Halbkreis zeigt nach unten: Pin-1 link, Pin-2 mittig, Pin-3 rechts !) \fP"
.in -1c
.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für WFO: Arduino Informatik-Schulprojekt aus dem Quellcode\&.
